### ISSUE TITLE
Colocation tasks before production

### ISSUE THREAD

**Issue by cowfee** [cowprotocol/services#1672]
## Before Staging
<details>
  <summary>✅</summary>

- Store CIP-20 data:
  - [x] Insert data into `settlement_observations` (looks like a trivial bug).
  - [x] Insert data into `solver_competition` (we have to build the JSON blob we store and also store that). https://github.com/cowprotocol/services/issues/1603 and update solver rewards script.
  - [x] Define new shape of solver_competition and save it to db https://github.com/cowprotocol/services/issues/1614
- [x] Respect auction deadline in the `solvers` crate. https://github.com/cowprotocol/services/issues/1664
- Sort orders in the driver before sending the auction to solvers:
  - [x] Sort market orders before limit orders.
  - [x] Sort well-priced orders before mispriced ones, using the reference prices provided in the auction. Make the sorting order randomized, weighted by how likely each order is to be settled. So more likely-to-settle orders will probably come first, and less likely-to-settle orders will come later, but the sorting order shouldn't be deterministic. Here's a [reference PR](https://github.com/cowprotocol/services/pull/762) which implemented this in the old code.
  - [x] Filter orders based on user balance. If the user doesn't have enough balance to settle an order, it should be filtered out. Note that if there are multiple orders from the same user, the later orders should be filtered out if the user's balance only covers the former orders. So the filtering should be context-aware.
- https://github.com/cowprotocol/services/issues/1666:
  - [x] Balancer.
    - [x] https://github.com/cowprotocol/services/pull/1698
    - [x] https://github.com/cowprotocol/services/pull/1700
    - [x] https://github.com/cowprotocol/services/pull/1701
    - [x] https://github.com/cowprotocol/services/pull/1702
  - [x] https://github.com/cowprotocol/services/pull/1670
- Fetch more token metadata in the driver (currently, the autopilot passes all this metadata to the driver, but in the future the driver should do this on its own):
  - [x] Token decimals.
  - [x] Token symbols.
  - [x] Token balance available in the settlement contract.
- [x] [Non blocking] Add `/reveal` to driver https://github.com/cowprotocol/services/issues/1744
- [x] Score calculation https://github.com/cowprotocol/services/issues/1893
</details>

## Before Production
- [ ] Make sure solver reward payout scripts work as expected
- [ ] cowprotocol/k8s-autodeploy#3
- [ ] cowprotocol/services#1949

## After Production (Cleanups)
- [ ] cowprotocol/services#1673
- [ ] Port ZeroEx LimitOrder Liquidity
