### ISSUE TITLE
feat: Protocol Fees Tracker

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#2114]
In first iteration, only the fee for out-of-market limit orders will be collected. Here is the current overview of the tasks needed to finish this project:

- [x] [Store quotes for limit orders](https://github.com/cowprotocol/services/issues/2078) - https://github.com/cowprotocol/services/pull/2087
- [x] [Define fee policies](https://github.com/cowprotocol/services/issues/2083) - https://github.com/cowprotocol/services/pull/2098
- [x] [Forward fee policies to driver](https://github.com/cowprotocol/services/issues/2084) - https://github.com/cowprotocol/services/pull/2098
- [x] [Skip in-market limit orders](https://github.com/cowprotocol/services/issues/2092) - https://github.com/cowprotocol/services/pull/2250
- [x] [Skip TWAP limit orders](https://github.com/cowprotocol/services/issues/2115) - 
- [x] [Store fee policies in database](https://github.com/cowprotocol/services/issues/2111) - https://github.com/cowprotocol/services/pull/2118
- [x] Adjust clearing prices in driver - https://github.com/cowprotocol/services/pull/2213
- [ ] [Nice to have] Fetch existing quote for order - 
- [ ] [Nice to have] Fetch fee policy for order -

**Comment by sunce86** [comment]
Closing as finished. The only leftover task is https://github.com/cowprotocol/services/issues/2267 which is not blocking the launch.
