### ISSUE TITLE
feat: Protocol Fees Tracker 2: PriceImprovement over Quotes

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#2287]
### Problem
In previous stage we implemented protocol fees for out-of-market limit orders: https://github.com/cowprotocol/services/issues/2114

In next stage we want to charge the fee from in-market orders (both market and limit orders).

## Tasks

- [x] Define new `PriceImprovement` fee policy in autopilot arguments. This fee policy should contain `factor`, `max_volume_cap`.
- [x] Construct the `PriceImprovement` fee policy in autopilot domain for each order and forward it to the `driver`. This time, fee policy additionally contains the attached `quote`.
- [x] Adjust protocol fee calculation in the driver to take quote into consideration.
- [ ] ~Implement custom clearing prices for market orders in SettlementEncoder. 
**WARNING**: this potentially requires A LOT of time. It would require allowing an order to have both signed `user_fee` and `surplus_fee` (through which we model protocol fees).~
- [x] Add new variant to database table `fee_policies` and implement storing https://github.com/cowprotocol/services/issues/2478
- [ ] Implement protocol fee calculation as seen onchain - https://github.com/cowprotocol/services/issues/2466
- [ ] Write integration tests - https://github.com/cowprotocol/services/issues/2479
- [ ] Write integration tests for partially fillable orders - https://github.com/cowprotocol/services/issues/2480
- [ ] Solver team: Update accounting part.

**Comment by fleupold** [comment]
> WARNING: this potentially requires A LOT of time. It would require allowing an order to have both signed user_fee and surplus_fee (through which we model protocol fees).

Maybe we should make this dependent on having shipped fee = 0 before then to avoid this work? (cc @olgafetisova & @harisang). Right now an order can either have a fixed user signed fee or a fee that is taken from the surplus, but never both.

**Comment by sunce86** [comment]
Do we also need to make sure integrators are not sending us the orders with user signed fee != 0? Otherwise, if we do not support protocol fees for those, then those orders will not pay protocol fees?

**Comment by sunce86** [comment]
> Do we also need to make sure integrators are not sending us the orders with user signed fee != 0? Otherwise, if we do not support protocol fees for those, then those orders will not pay protocol fees?

decided with @olgafetisova that it is fine to wait for fee=0 before releasing price improvements over quotes.

**Comment by fleupold** [comment]
Closing in favor of individual tasks
