### ISSUE TITLE
feat: Rank by Surplus Tracker

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#2382]
### Problem
Issue tracker for rank by surplus implementation.
Solutions ranking needs to be changed from `rank by score` to `rank by surplus`.

Here is how surplus is defined in the `driver`:
`surplus`- raw surplus that is defined by original clearing prices provided by solvers
`surplus' = surplus - surplus_fee`
`surplus'' = surplus' - protocol_fee`

So, we want to rank by `surplus'`. 

Tasks:
- [x] Implement ranking by surplus in the driver - https://github.com/cowprotocol/services/pull/2406
- [x] Add configuration parameter in the driver, that will be used to switch to CIP38 rules.

Nice to have:
- [ ] [After release] Drop `score` wherever used (from solvers interface for example). Keep it in the driver interface since it will be reused to report surplus to autopilot since autopilot won't calculate this but it will trust the driver - https://github.com/cowprotocol/services/issues/2493
- [ ] Also double check the delivered surplus in the autopilot based on the onchain data (to verify that the promised solution was delivered) - https://github.com/cowprotocol/services/issues/2494
- [ ] [After release] Remove temporary configuration - https://github.com/cowprotocol/services/issues/2462

**Comment by fleupold** [comment]
> Change the way the autopilot ranks the solutions

Currently the autopilot just accepts the score from the driver as true. Do we want to change this and have the autopilot compute surplus and fees?

**Comment by sunce86** [comment]
> > Change the way the autopilot ranks the solutions
> 
> Currently the autopilot just accepts the score from the driver as true. Do we want to change this and have the autopilot compute surplus and fees?

I would prefer so. If autopilot can calculate the surplus (or any other value we use for ranking) from the solution itself, then there is no need for additional field as part of the /solve response.

**Comment by sunce86** [comment]
This is somewhat aligned with the idea explained here: https://github.com/cowprotocol/services/issues/2225

**Comment by fleupold** [comment]
> there is no need for additional field as part of the /solve response.

Well, instead (at least as outlined in #2225) there is need for the entire encoded settlement (which is much more than the score). I think if the value can be computed by what we already send then sure let the autopilot verify it, but if not, I think it's fine to trust the driver with this (at the end of the day the driver could also "lie" about their encoded settlement)

**Comment by sunce86** [comment]
All tasks covered with individual issues so closing this one.
