### ISSUE TITLE
feat: Ext. solvers operating driver tracker

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#2716]
#### Competition
- [ ] Remove `/reveal` endpoint completely.
- [ ] Remove `uninternalized call_data` field from `settlement_call_data` db table.
- [ ] Move populating `internalized_call_data` ☝️  from competition time to settlement update.
- [ ] Remove `score` field from `/solve` response.
- [ ] Competition time: Autopilot to build `domain::Settlement` based on `/solve` response
- [ ] Competition time: Autopilot to calculate the `score` based on `domain::Settlement` instead of trusting the driver.
- [ ] Competition time: Autopilot to confirm that `/solve.orders` are not outside the auction

#### Postprocessing on settlement update
- [ ] Add autopilot configuration to define observable solver addresses
- [ ] Stabilize solver competition table - needed so that settlement update can fetch data from `/solve` response.
- [ ] Implement checks on settlement update (todo add types of checks)
- [ ] Implement circuit breaker on violation of checks

**Comment by fleupold** [comment]
>  Check on settlement update - solution settled before deadline

For this one I'd be a little careful and maybe not immediately circuit break (if you settle an auction 1h later sure, but if it's a few blocks past the deadline I'd give it a pass.

**Comment by MartinquaXD** [comment]
Just wanted to add that since there are already solvers which run their own driver we need to let them know in advance whenever we change the API between autopilot and driver. For the currently listed tasks that would be:
1. removing the `score` field
2. removing the `/reveal` endpoint

Both of these could be implemented without breaking existing drivers (just ignore the `score` field) but it would be good to let them know regardless.
