### ISSUE TITLE
Risk-Adjusted Solver Rewards

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#606]
We are in the process of adding risk-adjusted solver rewards to account for additional risk of settling large orders vs additional risk of settling small orders. Full details on the proposal can be found here: <https://forum.cow.fi/t/cip-draft-risk-adjusted-solver-rewards/1132>.

Specifically there is a function `f(coefficients, order) -> Reward` that computes an order reward from its two coefficients. We need to:
- Have the `solver` compute and specify rewards per order as part of the `instance.json` file.
- Store either the rewards or coefficient (as the order data is already available) in the database for solver payout computation

Concretely for the first deliverable:
* [x] Upload settlement competition before mining settlement transaction (this ensures we have competition and reward information for "lost transactions" that may get mined some time in the future). #608
* [x] Introduce new table for storing rewards per order per auction. #609
* [x] Upload order rewards to the new table (start by uploading a flat 35.0 so the analytics team can start testing). #611 
* [x] Add the order rewards to the `api/v1/auction` and `instance.json` (again, we can start by adding the flat 35.0 amount) #619 
* [x] Implement actual risk-adjusted reward computation and add configuration for setting risk coefficients. #627

**Comment by vkgnosis** [comment]
We have the estimated gas amount and current gas price at time of order creation in the order_quotes table. If an order doesn't have a quote it is a liquidity order and liquidity orders don't give rewards anyway. We do not delete quotes.
It could be a problem with limit orders in the future because they won't have quotes either.

We could store the coefficients in a new table based on what block range they are valid for.

There is a trade off between storing the least amount of data and future flexibility.
We could say that whenever we want to calculate an order's reward we are going to look in the quotes and coefficients table. The downside is that this becomes awkward if the formula changes and it is more work when you want to query the rewards.

Alternatively we can store the already computed rewards for all orders in an auction as mentioned in your last point. That way we duplicate some data but it is easier to make future changes.
Currently the autopilot creates a new auction every second so it would be too wasteful to store them for the majority of auctions that never go into solver competition. We can fix this by storing the rewards only when we have determined that we are going to settle a solution. This would eventually happen in the autopilot with solver-driver-colocation or until then in the driver in a similar way we handle storing solver competition info.
Thinking about this I remembered that initially we were storing competition info twice. First when we have picked a winning solution that should be settled and then again when we have found the mined transaction. At some point we switched to auto incrementing solver competition id so we had to stop doing this and only store when we find the mined transaction. This lead to competition info sometimes not getting stored if we for whatever reason didn't find the transaction (like driver restart). Now that we use an auction id we can go back to the original approach which would allow us to store the order rewards there too.
It might still be cleaner to use a new table for this to differentiate information we require, from the more optional, debug oriented competition info. Especially since the competition info is an opaque json blob.

**Comment by nlordell** [comment]
Discussed synchronously and determined:
1. We will start uploading settlement competition information **before** we start mining the transaction. This is because it is possible for mining to time out but we still want to record the auction and settlement competition information in those cases (just in case the transaction mines eventually).
2. We will introduce a new table:
    ```sql
    CREATE TABLE order_rewards (
        order_uid bytea,
        auction_id bigint,
        reward double precision
    );
    ```
3. Add code for uploading amounts to the order rewards table (should be done at the same time as uploading the initial settlement competition information, before we have a mined transaction).
4. Add the order rewards value to the `api/v1/auction` and `instance.json`
5. Implement the "real" computation based on configured coefficient values.

One remaining open question is that there are possibilities for ambiguity when matching `auction_id` to `settlement_transaction_hash` values. This is because it is possible for transactions to timeout, and, in the case where the same solver wins multiple settlements in a row with multiple timeouts, its not always obvious which auction transaction was actually mined. @vkgnosis and I assume that this happens rarely enough that we can initially, account for this manually. That being said, we will work on a more robust way to match auction IDs to settlement transactions moving forward (in a way that doesn't block a partial deliverable of the risk-adjusted settlement reward deliverable).

**Comment by nlordell** [comment]
Updated the issue with ☝️.


<details><summary>Previous list of tasks for reference...</summary>

Concretely, what needs to be defined is:
- Determine the database storage scheme to be able to retrieve/compute solver rewards after the fact (i.e. during solver payout). The formula envolves:
    1. The auction `gas_price` estimate (i.e. the estimated effective gas price that the settlement will execute with, which is included as part of the `auction` that is passed to the individual solvers)
    2. The order's `gas_amount` estimate (i.e. the estimated amount, in gas units, needed to settle an order directly)
    3. The risk-adjustment coefficients `a` and `b`.
    4. This should be done **FIRST** in order to unblock the data team (so they know how we intend on storing this in the database in order to already start working on their queries).
- Add the reward per order to the `instance.json` file that we send to external solvers. We can either:
    1. Compute the reward **per order** in the `autopilot` and share send it out as part of the `auction` (my preference).
    2. Include the coefficients in the `auction` and compute them locally in the `solver`/`driver`
    3. The initial implementation can just return the flat `35.0 COW` reward that is sent per
- Add configuration options for configuring the risk-adjustment coefficients in the `autopilot` and implement the actual risk-adjustment calculation.
- Store coefficients or per `(order, auction)` rewards in the database.

</details>

**Comment by vkgnosis** [comment]
How is this supposed to work for non ethereum mainnet networks? The CIP was written with mainnet in mind. Currently we store the 35 placeholder value for all networks.

**Comment by nlordell** [comment]
Initial risk-adjusted solver rewards implementation should be complete.
