### ISSUE TITLE
Simulate and use internal interactions for settlement competition.

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#635]
This issue captures the work for simulating, and using, internal interactions in settlements for the competition.

This is a _temporary_ work-around for dealing with internalized buffer interactions for exceedingly complex trading routes. Ideally, we need to capture the `maximize(surplus - cost)` objective for internalized trades as well as external ones. One easy way of doing this would be to include the internalized interaction when simulating for solver competition. This way, the cost of the internal interaction is accounted for in the settlement competition and would disincentivize paying 2M gas for a 1$ price improvement.

This, however, is not a long term solution and is incompatible with solvers bidding for rewards (since cost is not part of the objective function, and they have no revert risk for these trades as they use internal buffers).

### Work Items

* [x] Adding execution order to internal interactions - unfortunately another breaking solver-API change (oops - in retrospect, we should have accounted for this when adding the flag).
* [x] Including the internalized interactions as part of the settlement (#636)
* [x] When finalizing settlements, generating the “full” settlement as well as the “internalized” settlement.
* [x] Simulate with the “full” settlement but submit the “internalized” one.

**Comment by sunce86** [comment]
I think we can close this issue @harisang
