### ISSUE TITLE
Fill-or-kill Limit Orders

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#643]
This issue captures the work around fill-or-kill limit orders. Specifically, we want to add a new "class" of order such that:

| class     | filled w/ AMMs | surplus | fee-less | long-standing |
| --------- | -------------- | ------- | -------- | ------------- |
| market    | ✅             | ✅      | ❌        | ❌            |
| liquidity | ❌             | ❌      | ✅        | ✅            |
| **limit** | ✅             | ✅      | ❌        | ✅            |

With the the way the current fee mechanism works, long-standing orders are problematic. Since we compute fees at the time of order placement, a long-standing order is very likely to have an outdated fee amount by the time it gets executed.

With this in mind, we need a new fee machanism for limit orders that is different from market orders. Effectively, we no longer want to compute a pro-rated fee upfront, but instead have the protocol compute a "surplus fee" for every auction for every limit order. This dynamic "surplus fee" will be used to create a synthetic order to send to the solvers, meaning that no solver changes will be needed in order to implement this.

## Tasks

- [x] Introduce a new order `class` field for classifying different order kinds. We currently have market orders (`order.is_liquidity_order == false`) and liquidity orders (`order.is_liquidity_order == true`). We can likely replace the `is_liquidity_order` field with this new `class` field (as `order.is_liquidity_order && order.is_limit_order == true` does not make sense).
- [x] Classify orders where the `!liquidity_order_owners.contains(order.owner) && order.fee_amount == 0` as limit orders, and allow the placement of such orders. Note that we currently require orders to have `quote`s associated with them. This is not needed for limit orders (although the CoW Swap front end would like to be able to attach them by specifying a `quoteId` with the order for debugging purposes, but we shouldn't fall back to computing new quotes if none is provided).
- [x] For each auction, compute the `surplusFeeAmount` for each limit order. this represents the amount of fee that should be taken from surplus from the order. As I see it, there are two possibilities for where this can be computed, wither in the `solver`/`driver` or in the `autopilot`. I _think_ it should be computed in the `autopilot` so that:
  - API clients can query the current required `surplusFeeAmount` for their order (to know how much above market price their order needs to be in order to execute). This information can be displayed in the UI for example.
  - Means that the "protocol" determines the `surplusFeeAmount` instead of the batch builder. While this makes no difference at the moment, this is more important with [solver+driver colocation](https://github.com/cowprotocol/services/issues/337).
  - Existing `quote` machinery that already exists in the `autopilot` can be reused and doesn't need to be introduced in the `solver`/`driver` binary.
- [x] #703
- [x] #705
  - It might make sense to refactor the current `SettlementEncoder` abstraction to faciliate adding orders at different price points (instead of extending it to have yet another `limit_order_trades` vector analogue).
- [x] https://github.com/cowprotocol/services/issues/704
- [x] https://github.com/cowprotocol/services/issues/728 
- [x] https://github.com/cowprotocol/services/issues/753
- [x] https://github.com/cowprotocol/services/issues/740
- [x] https://github.com/cowprotocol/services/issues/731
- [x] https://github.com/cowprotocol/services/issues/729
- [x] https://github.com/cowprotocol/services/issues/766
- [x] https://github.com/cowprotocol/services/issues/767
- [x] https://github.com/cowprotocol/services/issues/769
- [x] https://github.com/cowprotocol/services/issues/771
 
## Bugs

- [x] https://github.com/cowprotocol/services/issues/770
- [x] https://github.com/cowprotocol/services/issues/777

## Nice to Haves

- [ ] https://github.com/cowprotocol/services/issues/765
- [x] https://github.com/cowprotocol/services/issues/807

## Needs Discussion

- [x] https://github.com/cowprotocol/services/issues/801

**Comment by vkgnosis** [comment]
Niksha (ennmichael) is doing the first task currently. Others still available but slightly dependent on it I guess.
