### ISSUE TITLE
[Ethflow] overview of left tasks

### ISSUE THREAD

**Issue by josojo** [cowprotocol/services#768]
I wanna put the information into a meta-issue, such that its easier to track progress:

Basic PRs needed:
- [x] e2e test refunder
- [x]  order cancellation indexing - https://github.com/cowprotocol/services/issues/708
- [x]  e2e test ethflow (done in #835) 
- [x] Contract changes: Make tx fail, if they are mined after the valid_to (1 day with updating services to the new contracts) (done in #851).
- [x] refactor refund status based on openapi - https://github.com/cowprotocol/services/issues/803
(See also PR discussions (https://github.com/cowprotocol/services/pull/723)) (2 days)
- [x] Make quotes unique in the backend. https://github.com/cowprotocol/services/issues/804 See [here](https://cowservices.slack.com/archives/C049GSMCTMW/p1667837475014909) (1 day) (no changes needed)
- [x] Create kube-config for refunder
- [x] onchain order - indexing failed indexes https://github.com/cowprotocol/services/issues/676 (3 day)
- [x]  Update kube-config two reflect 2 contracts - one staging and in prod (0 day)
- [x] Deploy the contracts in all networks (1 day)
- [x] Ask Auditor(Adam for an update of the report) (0 day) ([track here](https://cowservices.slack.com/archives/CM1HPMCE5/p1670255854192879)) (external link: https://github.com/cowprotocol/ethflowcontract/pull/43)
- [x] Ask for funds for the refunder from Nomev Labs (ask in normal finance channel, luis knows already about it)(0 day)
- [x] Enable alerts for low balances for refunder (0,5 day)
- [x] COW token holder discounts work for EthFlow orders (1 day) (note: this is (probably) an issue if receiver is not the owner. It isn't blocking orders ([discussion](https://cowservices.slack.com/archives/C049GSMCTMW/p1669906040936549))).

During the launch
- [x] Watch refunder behaviour and observe how often we have to refund. Make cost estimation

Future versions:
- [x]  Order creation timestamp based on block-timestamp instead of system-time while indexing
- [ ]  grafana metrics for refunder
- [ ]  tx-hash storing of order creation 
- [x]  tx-hash storing of order cancellation
